# koji-download-build.py packages list

# [packages]
rust-bootupd.debug = false
bootc.debug = false
ostree.debug = false
rpm-ostree.debug = false
podman.debug = false
buildah.debug = false
skopeo.debug = false
"python3.14".debug = false
libvirt.debug = false
qemu.debug = false
krb5.debug = false
gcc.debug = false
