FROM localhost/fedora-silverblue:43

# Keep container image for 3 weeks
#LABEL quay.expires-after=3w

LABEL org.opencontainers.image.title="Fedora SilverBlue 43 Testing"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue 43"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
#LABEL quay.expires-after=""

# Fix day/night background transition feature
#RUN sed --in-place="-ORIGINAL" 's/.png/.webp/g' /usr/share/backgrounds/f43/default/f43.xml && \
RUN <<EORUN
    set -xeuo pipefail
    mkdir --parents /etc/backgrounds/f43/default
    mv /usr/share/backgrounds/f43/default/f43.xml /etc/backgrounds/f43/default
    ln --symbolic /etc/backgrounds/f43/default/f43.xml /usr/share/backgrounds/f43/default

#RUN sed --in-place="-ORIGINAL" 's,<filename>/usr/share/backgrounds/f43/default/f43.xml</filename>,<filename>/etc/backgrounds/f43/default/f43.xml</filename>,' /usr/share/gnome-background-properties/f43.xml && \

#COPY --chmod=644 usr/lib/systemd/system/fedora-atomic-desktops-static-grub-migration.service usr/lib/systemd/system/fedora-atomic-desktops-static-grub-migration.service
#COPY --chmod=755 usr/libexec/fedora-atomic-desktops-static-grub-migration usr/libexec/fedora-atomic-desktops-static-grub-migration
#RUN systemctl enable fedora-atomic-desktops-static-grub-migration.service

#RUN rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2024-54d50c12c0 && \

    # This update has been unpushed. See ...
    dnf --assumeyes upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2025-d9291ca2c7

    rpm-ostree cleanup --repomd
    dnf clean all
    rm --recursive --force /var/* /tmp/*
    bootc container lint
EORUN
