FROM quay.io/fedora-ostree-desktops/silverblue:rawhide

LABEL org.opencontainers.image.title="Fedora SilverBlue RawHide"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue RawHide"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
#LABEL quay.expires-after=""

# Copy custom config to /usr & /etc
COPY usr usr
COPY etc etc

# - Install RPM Fusion Free and Nonfree Repositories
# - Install NVIDIA driver
# - Replace nano with vim
# - Remove plymouth
# - Replace noopenh264 with openh264
# - Install various packages
# - Enable libvirtd
# - Misc /var cleanup
# - Remove SetUID/SetGID bits

#RUN dnf --assumeyes install \
#    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm --eval %fedora).noarch.rpm \
#    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm --eval %fedora).noarch.rpm \
#    && \
RUN dnf --assumeyes remove plymouth plymouth-core-libs plymouth-graphic-libs \
    && \
    dnf swap --assumeyes --allowerasing nano vim-default-editor \
    && \
    dnf swap --assumeyes --allowerasing noopenh264 mozilla-openh264 \
    && \
    dnf --assumeyes install \
#        akmod-nvidia \
        htop \
        iotop \
        netcat \
        sysprof \
#        arm-image-installer \
        butane \
        coreos-installer \
        virt-install \
        virt-manager \
        smartmontools \
    && \
    systemctl enable libvirtd.socket \
    && \
    rm --recursive --force /var/lib/unbound/root.key \
    && \
    chmod ug-s \
        /usr/bin/chage \
        /usr/bin/chfn \
        /usr/bin/chsh \
        /usr/bin/gpasswd \
        /usr/bin/newgrp \
        /usr/bin/passwd \
        /usr/bin/vmware-user-suid-wrapper \
    && \
    rpm-ostree cleanup --repomd \
    && \
    dnf clean all \
    && \
    rm --recursive --force /var/* /tmp/*
