FROM quay.io/fedora-ostree-desktops/silverblue:41

LABEL org.opencontainers.image.title="Fedora SilverBlue 41"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue 41"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
