FROM quay.io/fedora-ostree-desktops/silverblue:42
#FROM quay.io/fedora/fedora-silverblue:42

# Keep container image for 3 weeks
#LABEL quay.expires-after=3w

LABEL org.opencontainers.image.title="Fedora SilverBlue 42"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue 42"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
#LABEL quay.expires-after=""

# Copy custom config to /usr & /etc
COPY usr usr
COPY etc etc
COPY fedora_packages.sh /tmp
COPY remove_fedora_packages.txt /tmp
# COPY install_fedora_packages.txt /tmp
COPY install_vscodium.sh /tmp

# - Install RPM Fusion Free and Nonfree Repositories
# - Install NVIDIA driver
# - Replace nano with vim
# - Remove plymouth
# - Replace noopenh264 with openh264
# - Remove and Install various packages
# - Enable libvirtd
# - Remove SetUID/SetGID bits
# - Cleanup

RUN <<EORUN
    set -xeuo pipefail
    mkdir --parents /etc/backgrounds/f42/default
    mv /usr/share/backgrounds/f42/default/f42.xml /etc/backgrounds/f42/default
    ln --symbolic /etc/backgrounds/f42/default/f42.xml /usr/share/backgrounds/f42/default

    /tmp/fedora_packages.sh
    /tmp/install_vscodium.sh

    rpm-ostree cleanup --repomd
    dnf clean all
    rm --recursive --force /var/* /tmp/*
    bootc container lint
EORUN
