FROM quay.io/fedora-ostree-desktops/silverblue:40

LABEL org.opencontainers.image.title="Fedora SilverBlue 40"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue 40"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"

# - Install dnf5
# - Install RPM Fusion Free and Nonfree Repositories
# - Install NVIDIA driver

RUN rpm-ostree install --apply-live --assumeyes --allow-inactive \
    dnf5 \
    dnf5-plugins \
#    dnf5-plugin-automatic \
    && \
    dnf5 --assumeyes install \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm --eval %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm --eval %fedora).noarch.rpm \
    akmod-nvidia \
    && \
    rpm-ostree cleanup --repomd \
    && \    
    dnf5 clean all
