#FROM quay.io/fedora-ostree-desktops/silverblue:41
# Temporary switch to quay.io/fedora/fedora-silverblue
FROM quay.io/fedora/fedora-silverblue:41

# Keep container image for 3 weeks
#LABEL quay.expires-after=3w

LABEL org.opencontainers.image.title="Fedora SilverBlue"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"

# Copy custom config to /usr & /etc
#COPY usr usr
#COPY etc etc

# - Replace noopenh264 with openh264
# - Install various packages
# - Enable libvirtd
# - Misc /var cleanup
# - Remove SetUID/SetGID bits
RUN dnf --version \
    rpm-ostree install --apply-live \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm --eval %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm --eval %fedora).noarch.rpm \
    && \
    rpm-ostree update \
        --uninstall rpmfusion-free-release \
        --uninstall rpmfusion-nonfree-release \
        --install rpmfusion-free-release \
        --install rpmfusion-nonfree-release
rpm-ostree override remove noopenh264 --install mozilla-openh264 \
    && \
    rpm-ostree override remove nano nano-default-editor --install vim-default-editor \
    && \
    rpm-ostree install \
        akmod-nvidia \
        htop \
        iotop \
        netcat \
        sysprof \
        krb5-workstation \
        arm-image-installer \
        coreos-installer \
        gnome-console \
        virt-install \
        virt-manager \
        smartmontools \
    && \
    systemctl enable libvirtd.socket \
    && \
    rm --recursive --force /var/lib/unbound/root.key \
    && \
    chmod ug-s \
        /usr/bin/chage \
        /usr/bin/chfn \
        /usr/bin/chsh \
        /usr/bin/gpasswd \
        /usr/bin/ksu \
        /usr/bin/newgrp \
        /usr/bin/passwd \
        /usr/bin/vmware-user-suid-wrapper \
    && \
    rpm-ostree cleanup --repomd
