FROM quay.io/fedora-ostree-desktops/silverblue:rawhide

LABEL org.opencontainers.image.title="Fedora SilverBlue RawHide"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue RawHide"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
