FROM localhost/fedora-silverblue:41

# Keep container image for 3 weeks
#LABEL quay.expires-after=3w

LABEL org.opencontainers.image.title="Fedora SilverBlue 41 Testing"
LABEL org.opencontainers.image.description="Customized image of Fedora SilverBlue 41"
LABEL org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
LABEL org.opencontainers.image.licenses="MIT"
#LABEL quay.expires-after=""

# Fix day/night background transition feature
RUN sed --in-place="-ORIGINAL" 's/f40/f41/g' /usr/share/backgrounds/f41/default/f41.xml && \

# - Remove ostree-grub2, setup composefs, rebuild initramfs
#RUN rpm-ostree --assumeyes override remove ostree-grub2 && \

#RUN rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2024-7bb17ff603 && \
#    && \

#RUN dnf --assumeyes upgrade --refresh --advisory=FEDORA-2024-deea72e2fd && \

#    dnf --assumeyes remove ostree-grub2 && \
#    echo -e "[composefs]\nenabled=yes" >> /usr/lib/ostree/prepare-root.conf && \
#    export KERNEL_VERSION="$(rpm --query --all kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
#    stock_arguments=$(lsinitrd "/lib/modules/${KERNEL_VERSION}/initramfs.img" | grep '^Arguments: ' | sed 's/^Arguments: //') && \
#    mkdir --parents /tmp/dracut /var/roothome && \
##    mkdir --parents /tmp/dracut /var/roothome /usr/lib/ostree-boot/efi/EFI && \
#    bash <(/usr/bin/echo "dracut $stock_arguments") && \
#    rm --recursive --force /var/* /tmp/*  && \
#    mv --verbose /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" #\
##    && \
##    /usr/bin/bootupctl backend generate-update-metadata \
##    && \
##    rpm-ostree cleanup --repomd
    rpm-ostree cleanup --repomd && dnf clean all && rm --recursive --force /var/* /tmp/*
