name: "Build Fedora Silverblue Image"

env:
  NAME: "fedora-silverblue"
  REGISTRY: "quay.io/operatement"
  BASEIMAGE: "quay.io/fedora-ostree-desktops/silverblue:43"
  # Temporary switch to quay.io/fedora/fedora-silverblue:43
  #BASEIMAGE: "quay.io/fedora/fedora-silverblue:43"

on:

  pull_request:
    branches:
      - main
    paths:
      - 'fedora-silverblue/**'
      - '.github/workflows/fedora-silverblue.yaml'

  push:
    branches:
      - main
    paths:
      - 'fedora-silverblue/**'
      - '.github/workflows/fedora-silverblue.yaml'

  schedule:
    - cron: '0 4 * * *'
    # Temporary switch to quay.io/fedora/fedora-silverblue:43
    #- cron: '30 13 * * *'

  workflow_dispatch:
    inputs:
      version:
        description: 'Override version label (org.opencontainers.image.version)'
        required: false
        default: ''

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  cancel-in-progress: true

jobs:
  build-push-image:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/podman/stable
      options: "--security-opt=label=disable --privileged --user 0:0 --device=/dev/kvm --device=/dev/fuse \
            --volume /:/run/host:rw --volume /mnt:/mnt --volume /var/run/docker.sock:/var/run/docker.sock \
            --workdir=/mnt"
    steps:

      # Reclaim disk space on the host
      - name: Reclaim disk space on the host
        run: |
          set -xeuo pipefail
          
          echo -e "\nAvailable disk storage:"
          sudo df -h
          # echo -e "\n"
          sudo ls -lah /run/host

          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host | sort --human-numeric-sort
          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /__e | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /mnt | sort --human-numeric-sort
          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /mnt/mnt | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/mnt | sort --human-numeric-sort
          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /__t | sort --human-numeric-sort
          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/opt | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/var | sort --human-numeric-sort
          # sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/usr | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/usr/local | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/usr/local/lib | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/usr/lib | sort --human-numeric-sort
          sudo du --human-readable --exclude="/proc" --exclude="/run/host/proc" --exclude="/run/host/var/lib/docker" --total --max-depth=1 /run/host/usr/share | sort --human-numeric-sort

          files=(
          "/run/host/usr/local/.ghcup"
          "/run/host/usr/local/graalvm"
          "/run/host/usr/local/man"
          "/run/host/usr/local/doc"
          "/run/host/usr/local/n"
          "/run/host/usr/local/aws-sam-cli"
          "/run/host/usr/local/aws-cli"
          "/run/host/usr/local/julia1.11.7"
          "/run/host/usr/local/lib/python3.12"
          "/run/host/usr/local/lib/node_modules"
          "/run/host/usr/local/lib/android"
          "/run/host/usr/local/share/powershell"
          "/run/host/usr/local/share/chromium"
          "/run/host/usr/share/javascript"
          "/run/host/usr/share/automake-1.16"
          "/run/host/usr/share/dbus-1"
          "/run/host/usr/share/google-cloud-sdk"
          "/run/host/usr/share/iso-codes"
          "/run/host/usr/share/lintian"
          "/run/host/usr/share/xml"
          "/run/host/usr/share/apache2"
          "/run/host/usr/share/autoconf"
          "/run/host/usr/share/groff"
          "/run/host/usr/share/info"
          "/run/host/usr/share/misc"
          "/run/host/usr/share/php"
          "/run/host/usr/share/grub"
          "/run/host/usr/share/python-wheels"
          "/run/host/usr/share/consolefonts"
          "/run/host/usr/share/fwupd"
          "/run/host/usr/share/bash-completion"
          "/run/host/usr/share/postgresql"
          "/run/host/usr/share/tcltk"
          "/run/host/usr/share/gtk-3.0"
          "/run/host/usr/share/zoneinfo"
          "/run/host/usr/share/swig4.0"
          "/run/host/usr/share/X11"
          "/run/host/usr/share/texinfo"
          "/run/host/usr/share/mime"
          "/run/host/usr/share/terminfo"
          "/run/host/usr/share/perl5"
          "/run/host/usr/share/mysql"
          "/run/host/usr/share/apache-maven-3.9.11"
          "/run/host/usr/share/ieee-data"
          "/run/host/usr/share/i18n"
          "/run/host/usr/share/perl"
          "/run/host/usr/share/python-babel-localedata"
          "/run/host/usr/share/fonts"
          "/run/host/usr/share/vim"
          "/run/host/usr/share/java"
          "/run/host/usr/share/icons"
          "/run/host/usr/share/mecab"
          "/run/host/usr/share/ri"
          "/run/host/usr/share/doc"
          "/run/host/usr/share/locale"
          "/run/host/usr/share/kotlinc"
          "/run/host/usr/share/man"
          "/run/host/usr/share/gradle-9.1.0"
          "/run/host/usr/share/az_12.5.0"
          "/run/host/usr/share/miniconda"
          "/run/host/usr/share/swift"
          "/run/host/usr/share/dotnet"
          "/run/host/usr/lib/apt"
          "/run/host/usr/lib/aspell"
          "/run/host/usr/lib/locale"
          "/run/host/usr/lib/apache2"
          "/run/host/usr/lib/cgi-bin"
          "/run/host/usr/lib/mysql"
          "/run/host/usr/lib/7zip"
          "/run/host/usr/lib/file"
          "/run/host/usr/lib/linux-azure-6.11-tools-6.11.0-1018"
          "/run/host/usr/lib/php"
          "/run/host/usr/lib/ruby"
          "/run/host/usr/lib/modules"
          "/run/host/usr/lib/postgresql"
          "/run/host/usr/lib/python3.12"
          "/run/host/usr/lib/snapd"
          "/run/host/usr/lib/gcc"
          "/run/host/usr/lib/python3"
          "/run/host/usr/lib/firefox"
          "/run/host/usr/lib/llvm-17"
          "/run/host/usr/lib/llvm-16"
          "/run/host/usr/lib/llvm-18"
          "/run/host/usr/lib/google-cloud-sdk"
          "/run/host/usr/lib/x86_64-linux-gnu"
          "/run/host/usr/lib/jvm"
          "/run/host/usr/games"
          "/run/host/var/spool"
          "/run/host/var/www"
          "/run/host/var/backups"
          "/run/host/opt"
          "/run/host/snap"
          "/run/host/__e"
          "/run/host/__t"
          )
          
          for file in ${files[@]}; do
            sudo rm -rf ${file}
          done
          sudo swapoff --all
          sudo rm -f /mnt/swapfile

          echo -e "\nAvailable disk storage:"
          sudo df -h
          # echo -e "\n"
          sudo ls -lah /run/host

      - name: Fixup GitHub homedir
        run: |
          set -xeuo pipefail
          mkdir -p /github/home/.docker/

      - name: Install tools in the container
        run: |
          set -xeuo pipefail
          dnf --refresh install -y \
            git-core jq rpm-ostree buildah skopeo \
            --exclude container-selinux --no-docs
          dnf clean all

      - name: Set alternate location of image store
        run: |
            set -xeuo pipefail
            sed -i 's/^\# imagestore = ""$/imagestore = "\/mnt"/' /usr/share/containers/storage.conf
            grep -E '^imagestore = ".*"$' /usr/share/containers/storage.conf

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Figure out version
        id: version
        run: |
          set -xexo pipefail
          if [[ -n ${VERSION} ]]; then
            version="${VERSION}"
          else
            version_base="$(skopeo inspect docker://${BASEIMAGE} | jq -r '.Labels."org.opencontainers.image.version"')"
            version_derived="$(skopeo inspect docker://${REGISTRY}/${NAME} | jq -r '.Labels."org.opencontainers.image.version"' || true)"
            if [[ -z "${version_derived}" ]]; then
              version="${version_base}"
            elif [[ "${version_base}" == "${version_derived}" ]]; then
              patch="${version_base##*\.}"
              ((patch++)) || true
              version="${version_base%\.*}.${patch}"
            else
              version="${version_base}"
            fi
          fi
          echo "Using version: ${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ inputs.version }}

      - name: Build Silverblue Container Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          # tags: '43'
          tags: build
          containerfiles: ${{ env.NAME }}/Containerfile-43
          context: ${{ env.NAME }}
          layers: false
          oci: true
          # labels: org.opencontainers.image.version=${{ steps.version.outputs.version }}

      - name: Rechunk container image
        run: |
          set -xexo pipefail
          # podman image rm quay.io/fedora-ostree-desktops/silverblue:43
          podman image prune --force --build-cache
          podman image prune --force
          # rpm-ostree experimental compose build-chunked-oci \
          rpm-ostree compose build-chunked-oci \
            --bootc --format-version=1 \
            --max-layers 96 \
            --from localhost/${NAME}:build \
            --output containers-storage:localhost/${NAME}:rechunked
          # echo "Available disk storage:"
          # df -h
          # du -h -d 1 "${PWD}" | sort -h

      - name: Write NOP Containerfile
        run: |
          set -xexo pipefail
          echo "FROM localhost/${NAME}:rechunked" > ${NAME}/Containerfile.labels

      - name: Add labels to container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          # tags: latest
          tags: '43'
          containerfiles: ${{ env.NAME }}/Containerfile.labels
          context: ${{ env.NAME }}
          layers: false
          oci: true
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.title="Fedora Silverblue 43"
            org.opencontainers.image.description="Customized image of Fedora Silverblue 43"
            org.opencontainers.image.source="https://github.com/GitHubAtomLearn/fedora-silverblue"
            org.opencontainers.image.licenses="MIT"

      # Silverblue 43 Container Image

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.10.0
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          auth_file_path: /tmp/auth.json

      - name: Push Silverblue Image to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          registry: ${{ env.REGISTRY }}
          tags: '43'
          extra-args: |
            --compression-format=zstd
        # --compression-level=19

      - name: Sign Silverblue Container Image
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ env.NAME }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
